set_property SRC_FILE_INFO {cfile:{C:/Users/kccistc/Desktop/april PJ/2025-april-team-Project/my_RISC-V.srcs/constrs_1/imports/working/MY_Basys-3-Master.xdc} rfile:../../../../../my_RISC-V.srcs/constrs_1/imports/working/MY_Basys-3-Master.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:9 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 10.000 -name sys_clk_pin -waveform {0.000 5.000} -add [get_ports clk]
set_property src_info {type:XDC file:1 line:91 export:INPUT save:INPUT read:READ} [current_design]
set_property PULLUP true [get_ports DHT11_DATA]
